# -*- coding: utf-8 -*-
"""WEEK3 A108260038 林昆霆.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15m7lLnN66_-ITl-stXrXUP0JpEEFc0-L
"""

print ("Hello world")

print ("I'm 林昆霆")